<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Incitec Pivot Ltd') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/assets/js/data-table/css/dataTables.scroller.css')
                        ->prependStylesheet($this->basePath() . '/assets/js/data-table/css/dataTables.responsive.css')
                        ->prependStylesheet($this->basePath() . '/assets/js/data-table/css/dataTables.colVis.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/js/data-table/css/dataTables.tableTools.css')
                        ->prependStylesheet($this->basePath() . '/assets/js/data-table/css/jquery.dataTables.css')
            			->prependStylesheet($this->basePath() . '/assets/js/switchery/switchery.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/style-responsive.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/style.css')
                        ->prependStylesheet($this->basePath() . '/assets/admin/css/style.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/slidebars.css') 
                        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
			->prependFile($this->basePath() . '/assets/js/jquery-1.11.1.min.js')
            ->prependFile($this->basePath() . '/assets/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/assets/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body class="sticky-header">
        <section>
            <!-- sidebar left start-->
            <div class="sidebar-left">
                <!--responsive view logo start-->
                <div class="logo dark-logo-bg visible-xs-* visible-sm-*">
                    <a href="/admin">
                        <img alt="Incitec" src="/images/logo-icon.png">
                        <!--<i class="fa fa-maxcdn"></i>-->
                    </a>
                </div>
                <!--responsive view logo end-->

                <div class="sidebar-left-info">
                    <!-- visible small devices start-->
                    <div class=" search-field">  </div>
                    <!-- visible small devices end-->

                    <!--sidebar nav start-->
                    <ul class="nav nav-pills nav-stacked side-navigation">
                        <li class="">
                            <h3 class="navigation-title">Navigation</h3>
                        </li>
                        <li class=""><a href="/admin"><i class="fa fa-home"></i> <span>Dashboard</span></a></li>
                        <?php echo $this->navigation('admin')->menu()->setUlClass('nav navbar-nav')->setPartial('partial/sidebar-nav.phtml'); ?>
                    </ul>
                    <!--sidebar nav end-->

                    <!--sidebar widget start-->
                    
                    <!--sidebar widget end-->

                </div>
            </div>
            <!-- sidebar left end-->

            <!-- body content start-->
            <div class="body-content" style="min-height: 1400px;">

                <div class="header-section">
                    <a class="toggle-btn"><i class="fa fa-outdent"></i></a>

                    <div class="right-notification">
                        <ul class="notification-menu">
                            <li>
                                
                            </li>

                            <li>
                                <a data-toggle="dropdown" class="btn btn-default dropdown-toggle" href="javascript:;">
                                    <span class="fa fa-user"></span>&nbsp; <?php echo $this->zfcUserIdentity()->getDisplayName() ?> <span class=" fa fa-angle-down"></span>
                                </a>
                                <ul class="dropdown-menu dropdown-usermenu purple pull-right">
                                    <li><a href="/user/logout"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>

                </div>

                <!--body wrapper start-->
                <?php echo $this->content; ?>
                <!--body wrapper end-->


                <!--footer section start-->
                <footer>
                    2015 &copy; Incitec Pivot Ltd.
                </footer>
                <!--footer section end-->

            </div>
            <!-- body content end-->
        </section>


    <?php echo $this->inlineScript()->prependFile($this->basePath('/assets/admin/js/script.js'))
                                    ->prependFile($this->basePath('/assets/js/scripts.js'))

                                    ->prependFile($this->basePath('/assets/js/data-table-init.js'))
                                    ->prependFile($this->basePath('/assets/js/data-table/js/dataTables.scroller.min.js'))
                                    ->prependFile($this->basePath('/assets/js/data-table/js/dataTables.responsive.min.js'))
                                    ->prependFile($this->basePath('/assets/js/data-table/js/dataTables.colVis.min.js'))
                                    ->prependFile($this->basePath('/assets/js/data-table/js/bootstrap-dataTable.js'))
                                    ->prependFile($this->basePath('/assets/js/data-table/js/dataTables.tableTools.min.js'))
                                    ->prependFile($this->basePath('/assets/js/data-table/js/jquery.dataTables.min.js'))

                                    ->prependFile($this->basePath('/assets/js/sparkline/sparkline-init.js'))
                                    ->prependFile($this->basePath('/assets/js/sparkline/jquery.sparkline.js'))
                                    ->prependFile($this->basePath('/assets/js/switchery/switchery-init.js'))
                                    ->prependFile($this->basePath('/assets/js/switchery/switchery.min.js'))
                                    ->prependFile($this->basePath('/assets/js/slidebars.min.js'))
                                    ->prependFile($this->basePath('/assets/js/switchery/switchery.min.js'))
                                    ->prependFile($this->basePath('/assets/js/jquery.nicescroll.js'))
                                    ->prependFile($this->basePath('/assets/js/modernizr.min.js'))
                                    ->prependFile($this->basePath('/assets/js/bootstrap.min.js'))
                                    ->prependFile($this->basePath('/assets/js/jquery-migrate.js'))
                                    ;
    ?>
    </body>
</html>
